In [283]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

from sklearn.feature_selection import chi2

In [285]:
df = pd.read_csv("dataset.csv")
df

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,5.0,3.0,2.0,1.0,2.0,2.0,1.0,5.0,5.0,1.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,4.0,4.0,2.0,1.0,1.0,1.0,2.0,3.0,5.0,4.0,...,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,5.0,5.0,2.0,2.0,3.0,4.0,5.0,3.0,5.0,3.0,...,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
3,5.0,3.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,...,22.0,172.0,59.0,1.0,female,right handed,college/bachelor degree,yes,city,house/bungalow
4,5.0,3.0,4.0,3.0,2.0,4.0,3.0,5.0,3.0,1.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,5.0,2.0,5.0,2.0,2.0,5.0,4.0,4.0,4.0,3.0,...,20.0,164.0,57.0,1.0,female,right handed,secondary school,no,city,house/bungalow
1006,4.0,4.0,5.0,1.0,3.0,4.0,1.0,4.0,1.0,1.0,...,27.0,183.0,80.0,5.0,male,left handed,masters degree,no,village,house/bungalow
1007,4.0,3.0,1.0,1.0,2.0,2.0,2.0,3.0,4.0,1.0,...,18.0,173.0,75.0,0.0,female,right handed,secondary school,yes,city,block of flats
1008,5.0,3.0,3.0,3.0,1.0,3.0,1.0,3.0,4.0,1.0,...,25.0,173.0,58.0,1.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,5.0,5.0,4.0,3.0,2.0,3.0,3.0,4.0,1.0,1.0,...,21.0,185.0,72.0,1.0,male,right handed,secondary school,no,village,house/bungalow

In [286]:
music_preferences = df.iloc[:, :19]
movie_preferences = df.iloc[:, 19:31]
hobbiesAnd_interests = df.iloc[:, 31:63]
phobias = df.iloc[:, 63:73]
health_habits = df.iloc[:, 73:76]
traits_views_opinions = df.iloc[:, 76:133]
spending_habits = df.iloc[:, 133:140]
demographics = df.iloc[:, 140:150]
hobbiesAnd_interests

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Passive sport,Active sport,Gardening,Celebrities,Shopping,Science and technology,Theatre,Fun with friends,Adrenaline sports,Pets
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,1.0,5.0,5.0,1.0,4.0,4.0,2.0,5.0,4.0,4.0
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,1.0,1.0,1.0,2.0,3.0,3.0,2.0,4.0,2.0,5.0
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,5.0,2.0,1.0,1.0,4.0,2.0,5.0,5.0,5.0,5.0
3,4.0,4.0,5.0,4.0,1.0,3.0,1.0,2.0,3.0,3.0,...,1.0,1.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,1.0
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,3.0,1.0,4.0,3.0,3.0,3.0,2.0,4.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,4.0,4.0,2.0,4.0,5.0,3.0,5.0,5.0,4.0,4.0
1006,4.0,1.0,1.0,5.0,4.0,5.0,5.0,2.0,2.0,1.0,...,1.0,5.0,5.0,1.0,2.0,5.0,1.0,5.0,1.0,5.0
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,2.0,2.0,1.0,1.0,2.0,3.0,2.0,3.0,1.0,5.0
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,2.0,4.0,1.0,3.0,5.0,5.0,5.0,5.0,1.0,4.0
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,5.0,4.0,5.0,3.0,3.0,3.0,1.0,5.0,2.0,5.0

In [287]:
#remove music and movie preferences from dataset
music_preferences = df.iloc[:, :19]
movie_preferences = df.iloc[:, 19:31]
df_copy = df.copy()
# df.drop(music_preferences, inplace=True, axis=1)
# df.drop(movie_preferences, inplace=True, axis=1)
df_copy.drop(music_preferences, inplace=True, axis=1)
df_copy.drop(movie_preferences, inplace=True, axis=1)
df_copy

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
3,4.0,4.0,5.0,4.0,1.0,3.0,1.0,2.0,3.0,3.0,...,22.0,172.0,59.0,1.0,female,right handed,college/bachelor degree,yes,city,house/bungalow
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,20.0,164.0,57.0,1.0,female,right handed,secondary school,no,city,house/bungalow
1006,4.0,1.0,1.0,5.0,4.0,5.0,5.0,2.0,2.0,1.0,...,27.0,183.0,80.0,5.0,male,left handed,masters degree,no,village,house/bungalow
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,18.0,173.0,75.0,0.0,female,right handed,secondary school,yes,city,block of flats
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,25.0,173.0,58.0,1.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,21.0,185.0,72.0,1.0,male,right handed,secondary school,no,village,house/bungalow

In [289]:
#Find the missing data in the columns
df_copy.isnull().sum()

History                   2
Psychology                5
Politics                  1
Mathematics               3
Physics                   3
                         ..
Left - right handed       3
Education                 1
Only child                2
Village - town            4
House - block of flats    4
Length: 119, dtype: int64

In [293]:
#Filling missing data
df_copy.fillna(0,axis=1,inplace=True)
df_copy.isnull().sum()

History                   0
Psychology                0
Politics                  0
Mathematics               0
Physics                   0
                         ..
Left - right handed       0
Education                 0
Only child                0
Village - town            0
House - block of flats    0
Length: 119, dtype: int64

In [298]:
#remove the demographics from dataset because we only want to focus on lifestyle behaviours
data = df_copy.iloc[:,:109]
data

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Parents' advice,Questionnaires or polls,Internet usage,Finances,Shopping centres,Branded clothing,Entertainment spending,Spending on looks,Spending on gadgets,Spending on healthy eating
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,4.0,3.0,few hours a day,3.0,4.0,5.0,3.0,3.0,1,3.0
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,2.0,3.0,few hours a day,3.0,4.0,1.0,4.0,2.0,5,2.0
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,3.0,1.0,few hours a day,2.0,4.0,1.0,4.0,3.0,4,2.0
3,4.0,4.0,5.0,4.0,1.0,3.0,1.0,2.0,3.0,3.0,...,2.0,4.0,most of the day,2.0,4.0,3.0,3.0,4.0,4,1.0
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,3.0,3.0,few hours a day,4.0,3.0,4.0,3.0,3.0,2,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,4.0,3.0,few hours a day,3.0,5.0,4.0,3.0,4.0,3,4.0
1006,4.0,1.0,1.0,5.0,4.0,5.0,5.0,2.0,2.0,1.0,...,4.0,3.0,less than an hour a day,3.0,1.0,1.0,1.0,1.0,5,3.0
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,4.0,5.0,most of the day,1.0,2.0,5.0,2.0,2.0,2,5.0
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,3.0,3.0,most of the day,3.0,2.0,1.0,5.0,3.0,3,3.0
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,3.0,5.0,few hours a day,5.0,4.0,2.0,3.0,1.0,1,5.0

In [299]:
#convert strings to numerical categories
columnList = ['Internet usage', 'Alcohol','Smoking']
data[columnList] = data[columnList].apply(lambda x: pd.factorize(x)[0])
#delete unwanted variables
data.pop('Lying')
data.pop('Punctuality')
data

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Parents' advice,Questionnaires or polls,Internet usage,Finances,Shopping centres,Branded clothing,Entertainment spending,Spending on looks,Spending on gadgets,Spending on healthy eating
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,4.0,3.0,0,3.0,4.0,5.0,3.0,3.0,1,3.0
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,2.0,3.0,0,3.0,4.0,1.0,4.0,2.0,5,2.0
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,3.0,1.0,0,2.0,4.0,1.0,4.0,3.0,4,2.0
3,4.0,4.0,5.0,4.0,1.0,3.0,1.0,2.0,3.0,3.0,...,2.0,4.0,1,2.0,4.0,3.0,3.0,4.0,4,1.0
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,3.0,3.0,0,4.0,3.0,4.0,3.0,3.0,2,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,4.0,3.0,0,3.0,5.0,4.0,3.0,4.0,3,4.0
1006,4.0,1.0,1.0,5.0,4.0,5.0,5.0,2.0,2.0,1.0,...,4.0,3.0,2,3.0,1.0,1.0,1.0,1.0,5,3.0
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,4.0,5.0,1,1.0,2.0,5.0,2.0,2.0,2,5.0
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,3.0,3.0,1,3.0,2.0,1.0,5.0,3.0,3,3.0
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,3.0,5.0,0,5.0,4.0,2.0,3.0,1.0,1,5.0

In [300]:
column_to_move = data.pop('Loneliness')
data.insert(106, 'Loneliness', column_to_move)
data

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Questionnaires or polls,Internet usage,Finances,Shopping centres,Branded clothing,Entertainment spending,Spending on looks,Spending on gadgets,Spending on healthy eating,Loneliness
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,3.0,0,3.0,4.0,5.0,3.0,3.0,1,3.0,3.0
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,3.0,0,3.0,4.0,1.0,4.0,2.0,5,2.0,2.0
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,1.0,0,2.0,4.0,1.0,4.0,3.0,4,2.0,5.0
3,4.0,4.0,5.0,4.0,1.0,3.0,1.0,2.0,3.0,3.0,...,4.0,1,2.0,4.0,3.0,3.0,4.0,4,1.0,5.0
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,3.0,0,4.0,3.0,4.0,3.0,3.0,2,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,3.0,0,3.0,5.0,4.0,3.0,4.0,3,4.0,4.0
1006,4.0,1.0,1.0,5.0,4.0,5.0,5.0,2.0,2.0,1.0,...,3.0,2,3.0,1.0,1.0,1.0,1.0,5,3.0,1.0
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,5.0,1,1.0,2.0,5.0,2.0,2.0,2,5.0,4.0
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,3.0,1,3.0,2.0,1.0,5.0,3.0,3,3.0,3.0
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,5.0,0,5.0,4.0,2.0,3.0,1.0,1,5.0,3.0

In [303]:
#separate the dependent variable and independent variables
x = data.iloc[:,:106]
y = data.iloc[:,106:]  #loneliness variable is the dependent variable
y

      Loneliness
0            3.0
1            2.0
2            5.0
3            5.0
4            3.0
...          ...
1005         4.0
1006         1.0
1007         4.0
1008         3.0
1009         3.0

[1010 rows x 1 columns]

In [304]:
from sklearn.model_selection import train_test_split

In [305]:
#split dataset into training and testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [310]:
f_score = chi2(x_train, y_train)
f_score[1]

array([8.98876123e-01, 5.15861162e-01, 1.60407212e-02, 5.60929807e-01,
       4.50291848e-01, 9.12074081e-01, 5.35497075e-01, 3.71109451e-01,
       7.42685825e-01, 8.22114037e-01, 2.62502614e-01, 2.10785448e-01,
       6.50461298e-01, 3.17330424e-01, 3.29245360e-02, 9.10614938e-02,
       5.43050227e-01, 1.80050820e-01, 7.56651730e-01, 4.45819979e-01,
       9.14972277e-02, 2.18306409e-04, 7.96674373e-01, 3.96721124e-03,
       4.37109384e-01, 9.88927803e-01, 7.33213459e-01, 6.21429070e-01,
       5.13655954e-01, 7.87064100e-01, 3.45195128e-01, 5.27613859e-01,
       3.40281556e-02, 8.57923278e-01, 7.59328194e-01, 5.58467538e-01,
       6.03223090e-01, 3.70437047e-01, 7.30754751e-01, 5.75253715e-03,
       2.21540074e-01, 9.56517955e-05, 1.90320508e-01, 7.60093395e-01,
       4.82402565e-01, 5.60958972e-01, 4.84918325e-01, 9.85638573e-01,
       8.78226228e-01, 6.71997674e-01, 7.89442667e-01, 9.84832050e-01,
       8.85405560e-01, 5.39960418e-01, 6.30977848e-01, 5.53044749e-01,
       1.63985701e-03, 4.02090824e-02, 6.25508935e-01, 1.79145469e-01,
       6.56715601e-03, 6.77209321e-01, 6.04283332e-03, 9.66464378e-01,
       2.72189565e-02, 8.37588529e-01, 5.25956666e-01, 8.53317299e-01,
       9.74535182e-01, 2.44463703e-01, 1.36262399e-07, 8.34073258e-01,
       7.34807131e-01, 5.07719142e-01, 2.15643529e-05, 3.41189799e-01,
       4.95016963e-02, 2.49586260e-06, 7.46984880e-01, 1.03935748e-01,
       9.93433694e-01, 9.63429112e-01, 7.34286823e-01, 3.37109918e-01,
       7.51302412e-02, 5.88771571e-01, 8.72638783e-02, 1.80684208e-02,
       9.80560127e-05, 6.42522646e-05, 5.06993066e-05, 7.50723889e-01,
       3.28675120e-01, 9.57172590e-01, 6.23101377e-01, 4.12625166e-03,
       9.11610293e-01, 2.12583715e-01, 4.26837851e-01, 5.16327724e-01,
       4.83183435e-01, 8.66684227e-03, 2.58843866e-01, 2.57247845e-01,
       2.48384860e-01, 6.87716726e-01])

In [314]:
pvalues = pd.Series(f_score[1])
pvalues.index = x_train.columns
pvalues

History                       0.898876
Psychology                    0.515861
Politics                      0.016041
Mathematics                   0.560930
Physics                       0.450292
                                ...
Branded clothing              0.008667
Entertainment spending        0.258844
Spending on looks             0.257248
Spending on gadgets           0.248385
Spending on healthy eating    0.687717
Length: 106, dtype: float64

In [315]:
pvalues.sort_values(ascending=False)

Achievements          9.934337e-01
Celebrities           9.889278e-01
Writing notes         9.856386e-01
Reliability           9.848321e-01
Cheating in school    9.745352e-01
                          ...
Happiness in life     6.425226e-05
Energy levels         5.069931e-05
Number of friends     2.156435e-05
Mood swings           2.495863e-06
Changing the past     1.362624e-07
Length: 106, dtype: float64

In [327]:
#select the variables that have p-value of less than 0.05 because it means they are significant and can be used as variable to the model
pvalues.head()

History        0.898876
Psychology     0.515861
Politics       0.016041
Mathematics    0.560930
Physics        0.450292
dtype: float64

In [375]:
features = []
list1 = []

features = list(pvalues[pvalues<0.05].index)

for i in pvalues:
    if i < 0.05:
        list1.append(i)

final_list = pd.Series(list1, index=features)
final_list

Politics                   1.604072e-02
Law                        3.292454e-02
Writing                    2.183064e-04
Active sport               3.967211e-03
Flying                     3.402816e-02
Ageing                     5.752537e-03
Fear of public speaking    9.565180e-05
Fake                       1.639857e-03
Criminal damage            4.020908e-02
Self-criticism             6.567156e-03
Hypochondria               6.042833e-03
Eating to survive          2.721896e-02
Changing the past          1.362624e-07
Number of friends          2.156435e-05
New environment            4.950170e-02
Mood swings                2.495863e-06
Unpopularity               1.806842e-02
Life struggles             9.805601e-05
Happiness in life          6.425226e-05
Energy levels              5.069931e-05
Interests or hobbies       4.126252e-03
Branded clothing           8.666842e-03
dtype: float64

In [376]:
pvalues['Happiness in life']

6.425226462333805e-05