In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [90]:
df = pd.read_csv("dataset.csv")
df

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,5.0,3.0,2.0,1.0,2.0,2.0,1.0,5.0,5.0,1.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,4.0,4.0,2.0,1.0,1.0,1.0,2.0,3.0,5.0,4.0,...,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,5.0,5.0,2.0,2.0,3.0,4.0,5.0,3.0,5.0,3.0,...,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
3,5.0,3.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,...,22.0,172.0,59.0,1.0,female,right handed,college/bachelor degree,yes,city,house/bungalow
4,5.0,3.0,4.0,3.0,2.0,4.0,3.0,5.0,3.0,1.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,5.0,2.0,5.0,2.0,2.0,5.0,4.0,4.0,4.0,3.0,...,20.0,164.0,57.0,1.0,female,right handed,secondary school,no,city,house/bungalow
1006,4.0,4.0,5.0,1.0,3.0,4.0,1.0,4.0,1.0,1.0,...,27.0,183.0,80.0,5.0,male,left handed,masters degree,no,village,house/bungalow
1007,4.0,3.0,1.0,1.0,2.0,2.0,2.0,3.0,4.0,1.0,...,18.0,173.0,75.0,0.0,female,right handed,secondary school,yes,city,block of flats
1008,5.0,3.0,3.0,3.0,1.0,3.0,1.0,3.0,4.0,1.0,...,25.0,173.0,58.0,1.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,5.0,5.0,4.0,3.0,2.0,3.0,3.0,4.0,1.0,1.0,...,21.0,185.0,72.0,1.0,male,right handed,secondary school,no,village,house/bungalow

In [91]:
#remove rows with null values on any columns
df = df.dropna(axis = 0, how ='any')

In [92]:
df

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,5.0,3.0,2.0,1.0,2.0,2.0,1.0,5.0,5.0,1.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,4.0,4.0,2.0,1.0,1.0,1.0,2.0,3.0,5.0,4.0,...,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,5.0,5.0,2.0,2.0,3.0,4.0,5.0,3.0,5.0,3.0,...,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
4,5.0,3.0,4.0,3.0,2.0,4.0,3.0,5.0,3.0,1.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow
5,5.0,3.0,2.0,3.0,2.0,3.0,3.0,2.0,5.0,5.0,...,20.0,186.0,77.0,1.0,male,right handed,secondary school,no,city,block of flats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,5.0,3.0,4.0,1.0,2.0,3.0,2.0,3.0,3.0,4.0,...,22.0,175.0,60.0,1.0,male,right handed,secondary school,no,city,block of flats
1005,5.0,2.0,5.0,2.0,2.0,5.0,4.0,4.0,4.0,3.0,...,20.0,164.0,57.0,1.0,female,right handed,secondary school,no,city,house/bungalow
1007,4.0,3.0,1.0,1.0,2.0,2.0,2.0,3.0,4.0,1.0,...,18.0,173.0,75.0,0.0,female,right handed,secondary school,yes,city,block of flats
1008,5.0,3.0,3.0,3.0,1.0,3.0,1.0,3.0,4.0,1.0,...,25.0,173.0,58.0,1.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,5.0,5.0,4.0,3.0,2.0,3.0,3.0,4.0,1.0,1.0,...,21.0,185.0,72.0,1.0,male,right handed,secondary school,no,village,house/bungalow

In [93]:
df.isnull().sum()

Music                       0
Slow songs or fast songs    0
Dance                       0
Folk                        0
Country                     0
                           ..
Left - right handed         0
Education                   0
Only child                  0
Village - town              0
House - block of flats      0
Length: 150, dtype: int64

In [94]:
music_preferences = df.iloc[:, :19]
movie_preferences = df.iloc[:, 19:31]
hobbiesAnd_interests = df.iloc[:, 31:63]
phobias = df.iloc[:, 63:73]
health_habits = df.iloc[:, 73:76]
traits_views_opinions = df.iloc[:, 76:133]
spending_habits = df.iloc[:, 133:140]
demographics = df.iloc[:, 140:150]
demographics

,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
4,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow
5,20.0,186.0,77.0,1.0,male,right handed,secondary school,no,city,block of flats
...,...,...,...,...,...,...,...,...,...,...
1004,22.0,175.0,60.0,1.0,male,right handed,secondary school,no,city,block of flats
1005,20.0,164.0,57.0,1.0,female,right handed,secondary school,no,city,house/bungalow
1007,18.0,173.0,75.0,0.0,female,right handed,secondary school,yes,city,block of flats
1008,25.0,173.0,58.0,1.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,21.0,185.0,72.0,1.0,male,right handed,secondary school,no,village,house/bungalow

In [95]:
#remove unwanted columns from dataset because we don't need them
df.drop(music_preferences, inplace=True, axis=1)
df.drop(movie_preferences, inplace=True, axis=1)
df.drop(phobias, inplace=True, axis=1)
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\1821399014.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(music_preferences, inplace=True, axis=1)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\1821399014.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(movie_preferences, inplace=True, axis=1)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\1821399014.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(phobias, inplace=True, axis=1)

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow
5,5.0,3.0,4.0,2.0,3.0,4.0,4.0,1.0,4.0,4.0,...,20.0,186.0,77.0,1.0,male,right handed,secondary school,no,city,block of flats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,3.0,4.0,1.0,2.0,2.0,5.0,5.0,3.0,3.0,2.0,...,22.0,175.0,60.0,1.0,male,right handed,secondary school,no,city,block of flats
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,20.0,164.0,57.0,1.0,female,right handed,secondary school,no,city,house/bungalow
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,18.0,173.0,75.0,0.0,female,right handed,secondary school,yes,city,block of flats
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,25.0,173.0,58.0,1.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,21.0,185.0,72.0,1.0,male,right handed,secondary school,no,village,house/bungalow

In [96]:
df.drop('Age', inplace=True, axis=1)
df.drop('Height', inplace=True, axis=1)
df.drop('Weight', inplace=True, axis=1)
df.drop('Number of siblings', inplace=True, axis=1)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\764305457.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Age', inplace=True, axis=1)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\764305457.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Height', inplace=True, axis=1)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\764305457.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Weight', inplace=True, axis=1)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\764305457.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Number of siblings', inplace=True, axis=1)

In [97]:
df

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Entertainment spending,Spending on looks,Spending on gadgets,Spending on healthy eating,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,3.0,3.0,1,3.0,female,right handed,college/bachelor degree,no,village,block of flats
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,4.0,2.0,5,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,4.0,3.0,4,2.0,female,right handed,secondary school,no,city,block of flats
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,3.0,3.0,2,4.0,female,right handed,secondary school,no,village,house/bungalow
5,5.0,3.0,4.0,2.0,3.0,4.0,4.0,1.0,4.0,4.0,...,3.0,1.0,4,4.0,male,right handed,secondary school,no,city,block of flats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,3.0,4.0,1.0,2.0,2.0,5.0,5.0,3.0,3.0,2.0,...,4.0,4.0,4,2.0,male,right handed,secondary school,no,city,block of flats
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,3.0,4.0,3,4.0,female,right handed,secondary school,no,city,house/bungalow
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,2.0,2.0,2,5.0,female,right handed,secondary school,yes,city,block of flats
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,5.0,3.0,3,3.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,3.0,1.0,1,5.0,male,right handed,secondary school,no,village,house/bungalow

In [73]:
#df.select_dtypes(np.number)
df

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Entertainment spending,Spending on looks,Spending on gadgets,Spending on healthy eating,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,3.0,3.0,1,3.0,female,right handed,college/bachelor degree,no,village,block of flats
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,4.0,2.0,5,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,4.0,3.0,4,2.0,female,right handed,secondary school,no,city,block of flats
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,3.0,3.0,2,4.0,female,right handed,secondary school,no,village,house/bungalow
5,5.0,3.0,4.0,2.0,3.0,4.0,4.0,1.0,4.0,4.0,...,3.0,1.0,4,4.0,male,right handed,secondary school,no,city,block of flats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,3.0,4.0,1.0,2.0,2.0,5.0,5.0,3.0,3.0,2.0,...,4.0,4.0,4,2.0,male,right handed,secondary school,no,city,block of flats
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,3.0,4.0,3,4.0,female,right handed,secondary school,no,city,house/bungalow
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,2.0,2.0,2,5.0,female,right handed,secondary school,yes,city,block of flats
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,5.0,3.0,3,3.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,3.0,1.0,1,5.0,male,right handed,secondary school,no,village,house/bungalow

In [98]:
#Convert the columns with categories into labels
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
columns = ['Gender','Left - right handed','Education','Only child','Village - town','House - block of flats','Internet usage', 'Alcohol','Smoking','Lying','Punctuality']

In [99]:
enc.fit(df[columns])

OrdinalEncoder()

In [100]:
df[columns] = enc.transform(df[columns])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\1327454402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[columns] = enc.transform(df[columns])

In [101]:
df.dtypes

History                   float64
Psychology                float64
Politics                  float64
Mathematics               float64
Physics                   float64
                           ...
Left - right handed       float64
Education                 float64
Only child                float64
Village - town            float64
House - block of flats    float64
Length: 105, dtype: object

In [103]:
column_to_move = df.pop('Loneliness')
df.insert(104, 'Loneliness', column_to_move)

In [104]:
df

,History,Psychology,Politics,Mathematics,Physics,Internet,PC,Economy Management,Biology,Chemistry,...,Spending on looks,Spending on gadgets,Spending on healthy eating,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats,Loneliness
0,1.0,5.0,1.0,3.0,3.0,5.0,3.0,5.0,3.0,3.0,...,3.0,1,3.0,0.0,1.0,0.0,0.0,1.0,0.0,3.0
1,1.0,3.0,4.0,5.0,2.0,4.0,4.0,5.0,1.0,1.0,...,2.0,5,2.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
2,1.0,2.0,1.0,5.0,2.0,4.0,2.0,4.0,1.0,1.0,...,3.0,4,2.0,0.0,1.0,5.0,0.0,0.0,0.0,5.0
4,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,...,3.0,2,4.0,0.0,1.0,5.0,0.0,1.0,1.0,3.0
5,5.0,3.0,4.0,2.0,3.0,4.0,4.0,1.0,4.0,4.0,...,1.0,4,4.0,1.0,1.0,5.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,3.0,4.0,1.0,2.0,2.0,5.0,5.0,3.0,3.0,2.0,...,4.0,4,2.0,1.0,1.0,5.0,0.0,0.0,0.0,3.0
1005,4.0,4.0,2.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,...,4.0,3,4.0,0.0,1.0,5.0,0.0,0.0,1.0,4.0
1007,2.0,3.0,3.0,3.0,1.0,3.0,4.0,1.0,1.0,1.0,...,2.0,2,5.0,0.0,1.0,5.0,1.0,0.0,0.0,4.0
1008,3.0,5.0,3.0,1.0,1.0,5.0,4.0,3.0,3.0,3.0,...,3.0,3,3.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0
1009,2.0,3.0,1.0,2.0,2.0,4.0,2.0,1.0,5.0,3.0,...,1.0,1,5.0,1.0,1.0,5.0,0.0,1.0,1.0,3.0

In [110]:
#separate the dependent variable and independent variables
x = df.iloc[:,:104]
y = df.iloc[:,104:]  #loneliness variable is the dependent variable
y

      Loneliness
0            3.0
1            2.0
2            5.0
4            3.0
5            2.0
...          ...
1004         3.0
1005         4.0
1007         4.0
1008         3.0
1009         3.0

[674 rows x 1 columns]

In [112]:
from sklearn.feature_selection import chi2

In [113]:
chi_scores = chi2(x,y)

In [114]:
chi_scores

(array([ 1.31790489,  2.63031701,  5.15100998,  3.18303684,  3.84285717,
         0.88318806,  2.2578909 ,  6.83591874,  4.5815485 ,  4.40186959,
         5.93124497,  3.86362513,  1.4275116 ,  3.34756422,  5.21359141,
        11.43861483,  2.59613663,  1.57670967,  2.97743257,  2.5185532 ,
         5.03739749, 27.83178484,  1.78317659,  8.08727613,  5.681764  ,
         1.68115676,  1.37494641,  0.27701639,  0.75788943,  2.67443067,
         3.71704546,  0.45451304,  9.31794126,  3.41878914,  3.45107626,
         1.06223617,  3.7656228 ,  1.05547951,  1.35408214,  2.02244528,
         3.22091042,  0.37703292,  0.70516412,  2.58956441,  2.42293564,
         2.93750065, 20.78742194,  9.98242767,  2.29673619,  6.50929396,
        15.06506464,  1.40874454, 12.76054841,  0.48086717, 10.13770308,
         1.88764052,  2.75790649,  1.54367498,  1.65759615,  4.65484002,
        31.21347986,  2.0363798 ,  4.93884396,  5.06010923, 29.83481185,
         5.44367741,  5.56152462,  1.64494281,  7.59186658, 27.63163898,
         0.74094502,  8.52745955,  0.78999287,  1.7553722 ,  0.53125546,
         2.28092405, 12.6437626 ,  1.02882296,  9.22830032,  7.14778408,
        15.88737466, 27.4105585 , 25.99145826,  2.7486802 ,  5.25962762,
         0.96486456,  3.93591654, 12.69061797,  0.85336212,  4.05576119,
         7.70014961,  3.91586199,  1.48836212, 12.79557142,  8.20525613,
         3.51061256,  1.74506982,  1.41045104,  3.5337466 ,  0.2894239 ,
         3.57493562,  3.17356716,  1.31664524,  1.26429274]),
 array([8.58330462e-01, 6.21462100e-01, 2.72150905e-01, 5.27675137e-01,
        4.27690342e-01, 9.26960279e-01, 6.88445800e-01, 1.44817426e-01,
        3.32987150e-01, 3.54342293e-01, 2.04342117e-01, 4.24776679e-01,
        8.39399550e-01, 5.01431577e-01, 2.66075296e-01, 2.20526538e-02,
        6.27507656e-01, 8.12971907e-01, 5.61609081e-01, 6.41316665e-01,
        2.83481759e-01, 1.34913048e-05, 7.75558821e-01, 8.84329709e-02,
        2.24208249e-01, 7.94137610e-01, 8.48537551e-01, 9.91249123e-01,
        9.44002743e-01, 6.13696274e-01, 4.45651614e-01, 9.77775375e-01,
        5.36256049e-02, 4.90333568e-01, 4.85356191e-01, 9.00216632e-01,
        4.38653530e-01, 9.01270003e-01, 8.52135184e-01, 7.31630391e-01,
        5.21560190e-01, 9.84313728e-01, 9.50690556e-01, 6.28672852e-01,
        6.58486438e-01, 5.68338411e-01, 3.48926439e-04, 4.07247282e-02,
        6.81363347e-01, 1.64205730e-01, 4.56815384e-03, 8.42673759e-01,
        1.25070423e-02, 9.75336634e-01, 3.81708878e-02, 7.56415072e-01,
        5.99120419e-01, 8.18877849e-01, 7.98405141e-01, 3.24580150e-01,
        2.76925758e-06, 7.29067558e-01, 2.93630244e-01, 2.81185335e-01,
        5.28841117e-06, 2.44724820e-01, 2.34374116e-01, 8.00692814e-01,
        1.07725930e-01, 1.48112431e-05, 9.46185224e-01, 7.40592437e-02,
        9.39784603e-01, 7.80636334e-01, 9.70387792e-01, 6.84244261e-01,
        1.31542024e-02, 9.05394446e-01, 5.56396091e-02, 1.28281585e-01,
        3.17407391e-03, 1.64189782e-05, 3.17703558e-05, 6.00723478e-01,
        2.61680115e-01, 9.15076044e-01, 4.14748069e-01, 1.28907264e-02,
        9.31154328e-01, 3.98511989e-01, 1.03200593e-01, 4.17512432e-01,
        8.28700953e-01, 1.23190925e-02, 8.43422502e-02, 4.76266517e-01,
        7.82515279e-01, 8.42376556e-01, 4.72765687e-01, 9.90486624e-01,
        4.66576064e-01, 5.29210854e-01, 8.58545158e-01, 8.67404005e-01]))

In [119]:
#higher the chi value, higher the importance
chi_values = pd.Series(chi_scores[0], index = x.columns)
chi_values.sort_values(ascending=False)

Changing the past         31.213480
Number of friends         29.834812
Writing                   27.831785
Mood swings               27.631639
Happiness in life         27.410558
                            ...
Empathy                    0.480867
Pets                       0.454513
Reliability                0.377033
Left - right handed        0.289424
Science and technology     0.277016
Length: 104, dtype: float64

In [121]:
#p values less than 0.05 is significant
p_values = pd.Series(chi_scores[1], index = x.columns)
p_values.sort_values(ascending=False)

Science and technology    0.991249
Left - right handed       0.990487
Reliability               0.984314
Pets                      0.977775
Empathy                   0.975337
                            ...
Happiness in life         0.000016
Mood swings               0.000015
Writing                   0.000013
Number of friends         0.000005
Changing the past         0.000003
Length: 104, dtype: float64

In [124]:
features = []
list1 = []

features = list(p_values[p_values<=0.05].index)

for i in p_values:
    if i < 0.05:
        list1.append(i)

final_list = pd.Series(list1, index=features)
final_list

Cars                    0.022053
Writing                 0.000013
Fake                    0.000349
Criminal damage         0.040725
Self-criticism          0.004568
Hypochondria            0.012507
Eating to survive       0.038171
Changing the past       0.000003
Number of friends       0.000005
Mood swings             0.000015
Getting angry           0.013154
Life struggles          0.003174
Happiness in life       0.000016
Energy levels           0.000032
Interests or hobbies    0.012891
Branded clothing        0.012319
dtype: float64

In [127]:
list(features)

['Cars',
 'Writing',
 'Fake',
 'Criminal damage',
 'Self-criticism',
 'Hypochondria',
 'Eating to survive',
 'Changing the past',
 'Number of friends',
 'Mood swings',
 'Getting angry',
 'Life struggles',
 'Happiness in life',
 'Energy levels',
 'Interests or hobbies',
 'Branded clothing']

In [136]:
drop_list = df.loc[:, ~df.columns.isin(['Cars','Writing','Fake','Criminal damage','Self-criticism','Hypochondria','Eating to survive','Changing the past','Number of friends','Mood swings','Getting angry','Life struggles','Happiness in life','Energy levels','Interests or hobbies','Branded clothing','Loneliness'])]

In [138]:
print(list(drop_list))

['History', 'Psychology', 'Politics', 'Mathematics', 'Physics', 'Internet', 'PC', 'Economy Management', 'Biology', 'Chemistry', 'Reading', 'Geography', 'Foreign languages', 'Medicine', 'Law', 'Art exhibitions', 'Religion', 'Countryside, outdoors', 'Dancing', 'Musical instruments', 'Passive sport', 'Active sport', 'Gardening', 'Celebrities', 'Shopping', 'Science and technology', 'Theatre', 'Fun with friends', 'Adrenaline sports', 'Pets', 'Smoking', 'Alcohol', 'Healthy eating', 'Daily events', 'Prioritising workload', 'Writing notes', 'Workaholism', 'Thinking ahead', 'Final judgement', 'Reliability', 'Keeping promises', 'Loss of interest', 'Friends versus money', 'Funniness', 'Decision making', 'Elections', 'Judgment calls', 'Empathy', 'Giving', 'Compassion to animals', 'Borrowed stuff', 'Cheating in school', 'Health', 'God', 'Dreams', 'Charity', 'Punctuality', 'Lying', 'Waiting', 'New environment', 'Appearence and gestures', 'Socializing', 'Achievements', 'Responding to a serious letter', 'Children', 'Assertiveness', 'Knowing the right people', 'Public speaking', 'Unpopularity', 'Small - big dogs', 'Personality', 'Finding lost valuables', 'Getting up', "Parents' advice", 'Questionnaires or polls', 'Internet usage', 'Finances', 'Shopping centres', 'Entertainment spending', 'Spending on looks', 'Spending on gadgets', 'Spending on healthy eating', 'Gender', 'Left - right handed', 'Education', 'Only child', 'Village - town', 'House - block of flats']

In [139]:
df.drop(drop_list, inplace=True, axis=1)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4548\4032145311.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(drop_list, inplace=True, axis=1)

In [140]:
df

,Cars,Writing,Fake,Criminal damage,Self-criticism,Hypochondria,Eating to survive,Changing the past,Number of friends,Mood swings,Getting angry,Life struggles,Happiness in life,Energy levels,Interests or hobbies,Branded clothing,Loneliness
0,1.0,2.0,1.0,1.0,1.0,1.0,1,1.0,3,3.0,1.0,1.0,4.0,5.0,3.0,5.0,3.0
1,2.0,1.0,2.0,1.0,4.0,1.0,1,4.0,3,4.0,5.0,1.0,4.0,3.0,3.0,1.0,2.0
2,1.0,5.0,4.0,1.0,4.0,1.0,5,5.0,3,4.0,4.0,4.0,4.0,4.0,5.0,1.0,5.0
4,3.0,1.0,2.0,1.0,5.0,1.0,1,4.0,3,2.0,2.0,2.0,3.0,5.0,3.0,4.0,3.0
5,5.0,1.0,1.0,4.0,4.0,1.0,2,3.0,3,3.0,3.0,3.0,3.0,4.0,5.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,2.0,1.0,1.0,4.0,3.0,4.0,3,3.0,5,3.0,3.0,2.0,3.0,3.0,5.0,3.0,3.0
1005,1.0,4.0,3.0,2.0,2.0,1.0,1,1.0,3,3.0,2.0,4.0,4.0,3.0,4.0,4.0,4.0
1007,1.0,1.0,1.0,5.0,5.0,1.0,1,5.0,1,2.0,2.0,5.0,3.0,1.0,1.0,5.0,4.0
1008,1.0,4.0,1.0,1.0,3.0,1.0,3,3.0,3,4.0,4.0,5.0,3.0,2.0,3.0,1.0,3.0
1009,3.0,2.0,4.0,2.0,3.0,3.0,4,1.0,2,2.0,1.0,2.0,4.0,2.0,2.0,2.0,3.0

In [147]:
X = df.iloc[:,:16]
Y = df.iloc[:,16:].values.ravel()  #loneliness variable is the dependent variable
Y

array([3., 2., 5., 3., 2., 3., 2., 2., 2., 4., 5., 2., 2., 2., 4., 2., 2.,
       4., 3., 4., 2., 4., 3., 3., 2., 2., 1., 3., 2., 3., 2., 4., 4., 3.,
       1., 3., 3., 4., 5., 4., 3., 3., 3., 3., 3., 2., 3., 4., 4., 1., 1.,
       3., 3., 2., 4., 3., 3., 3., 3., 2., 1., 3., 3., 3., 5., 3., 4., 5.,
       3., 3., 4., 4., 2., 5., 5., 3., 3., 3., 1., 2., 4., 5., 4., 3., 5.,
       3., 2., 5., 4., 3., 2., 2., 2., 2., 3., 3., 4., 3., 5., 2., 3., 5.,
       2., 5., 3., 4., 4., 3., 4., 2., 2., 3., 5., 2., 5., 5., 2., 5., 3.,
       5., 4., 1., 3., 5., 4., 4., 5., 4., 3., 3., 2., 2., 5., 2., 5., 4.,
       4., 5., 3., 3., 3., 2., 1., 5., 3., 3., 3., 3., 4., 3., 3., 2., 4.,
       4., 3., 3., 4., 2., 2., 5., 2., 4., 3., 1., 3., 2., 2., 5., 4., 3.,
       2., 2., 2., 3., 2., 2., 3., 2., 3., 3., 2., 5., 4., 5., 1., 2., 2.,
       4., 1., 3., 4., 1., 2., 3., 2., 3., 3., 2., 4., 4., 3., 5., 4., 3.,
       1., 2., 3., 3., 4., 2., 3., 4., 2., 1., 4., 3., 2., 2., 4., 3., 3.,
       5., 2., 3., 3., 2., 3., 2., 1., 2., 4., 3., 3., 1., 3., 5., 3., 5.,
       3., 5., 4., 2., 2., 3., 2., 5., 2., 2., 3., 2., 3., 2., 4., 4., 1.,
       1., 3., 3., 1., 3., 4., 3., 2., 1., 2., 4., 4., 3., 2., 1., 2., 3.,
       3., 3., 2., 3., 1., 3., 4., 3., 3., 3., 1., 2., 2., 4., 4., 1., 2.,
       2., 5., 2., 2., 5., 3., 1., 5., 5., 2., 2., 2., 3., 5., 1., 3., 4.,
       3., 3., 4., 3., 4., 3., 5., 5., 1., 3., 4., 4., 4., 2., 3., 4., 2.,
       3., 1., 1., 2., 4., 1., 3., 3., 2., 3., 5., 2., 1., 2., 3., 1., 5.,
       3., 1., 2., 3., 1., 3., 3., 5., 2., 3., 3., 3., 4., 4., 3., 1., 2.,
       1., 4., 2., 3., 3., 3., 3., 4., 2., 3., 4., 1., 4., 3., 3., 4., 2.,
       4., 3., 1., 2., 1., 5., 1., 5., 4., 3., 1., 5., 3., 3., 4., 3., 5.,
       3., 2., 3., 4., 3., 1., 3., 4., 2., 2., 3., 4., 3., 3., 4., 3., 4.,
       2., 3., 3., 1., 2., 5., 5., 2., 4., 2., 4., 3., 5., 1., 3., 3., 1.,
       4., 3., 1., 5., 2., 4., 2., 1., 3., 4., 3., 1., 2., 5., 3., 4., 5.,
       3., 2., 4., 5., 3., 3., 4., 1., 2., 2., 3., 5., 2., 3., 3., 3., 4.,
       2., 3., 4., 3., 3., 3., 3., 2., 4., 3., 3., 4., 1., 5., 3., 4., 3.,
       2., 3., 5., 3., 1., 5., 3., 1., 4., 3., 2., 2., 3., 3., 1., 3., 3.,
       3., 2., 1., 3., 4., 2., 1., 4., 1., 2., 4., 1., 3., 2., 3., 2., 3.,
       2., 2., 1., 3., 3., 2., 1., 1., 2., 4., 3., 3., 1., 3., 2., 4., 2.,
       5., 1., 3., 3., 3., 3., 2., 3., 2., 3., 1., 3., 2., 5., 3., 4., 2.,
       1., 2., 3., 3., 2., 1., 2., 4., 2., 1., 5., 2., 1., 2., 4., 3., 5.,
       1., 3., 2., 5., 3., 2., 3., 1., 1., 2., 2., 2., 4., 1., 2., 1., 3.,
       3., 2., 2., 3., 1., 3., 4., 2., 3., 2., 4., 1., 3., 2., 4., 3., 2.,
       2., 2., 3., 4., 4., 2., 2., 3., 2., 2., 2., 2., 3., 2., 2., 2., 1.,
       3., 3., 5., 2., 4., 5., 3., 4., 2., 3., 3., 4., 1., 2., 3., 3., 5.,
       4., 2., 4., 4., 5., 5., 2., 4., 2., 3., 2., 3., 4., 3., 4., 1., 2.,
       1., 5., 2., 2., 2., 1., 2., 2., 4., 2., 4., 3., 3., 3., 5., 2., 2.,
       3., 4., 2., 3., 2., 3., 3., 4., 4., 3., 3.])

In [148]:
#split into training and testing
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

In [149]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train) 
x_test = sc_x.transform(x_test)

In [150]:
#train the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)

In [151]:
model.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [152]:
model.score(x_test, y_test)

0.3905325443786982

In [153]:
y_pred = model.predict(x_test)

In [154]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print("Confusion Matrix : \n", cm)

Confusion Matrix :
 [[ 7  9  7  0  0]
 [ 2 17 18  2  0]
 [ 2 14 33  5  0]
 [ 0  4 23  3  7]
 [ 0  0  9  1  6]]

In [155]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.3905325443786982

In [156]:
#Train model using Naives Bayes
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

# fit the model
gnb.fit(x_train, y_train)

GaussianNB()

In [157]:
gnb.score(x_test, y_test)

0.39644970414201186

In [158]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [159]:
y_pred1 = classifier.predict(x_test)

In [160]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm1 = confusion_matrix(y_test, y_pred1)
ac = accuracy_score(y_test,y_pred1)

In [161]:
cm1

array([[ 6, 10,  7,  0,  0],
       [ 3, 23, 10,  3,  0],
       [ 3, 22, 25,  4,  0],
       [ 0,  7, 24,  4,  2],
       [ 0,  2,  8,  5,  1]], dtype=int64)

In [162]:
ac

0.34911242603550297

In [163]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred2=clf.predict(x_test)

In [164]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred2))

Accuracy: 0.30177514792899407